### ISSUE TITLE
Dockerfiles - production and development

### ISSUE THREAD

**Issue by MJGTwo** [hbh7/MITRGroupProject_Frontend#5]
The following adjustments must be made for `Dockerfile` to be used as a development image:

- [x]  Add a version number tag (e.g. lts) to `FROM node` to allow for version control of the build environment
- [x] Add a `.dockerignore` to ignore files/folders such as `.env.example`, `.git` etc. 
- [x] Correct the script `CMD npm run prod` to `CMD ["npm", "run", "prod"]`, which is a production standard
- [x] Correct `package.json` script called `prod` to be a dev script to automatically transpile the code and not build the app.

The following additions must be made for `Dockerfile-prod` to be used as a production image:

- [x] All of the previous requirements for the development image
- [x] Define the first image as a "builder" (i.e. `FROM node:12.14.1 AS builder`)
- [x] Add `RUN npm build` to 1) transpile TS into JS, 2) bundle the node_modules with the production code
- [x] Create a second layer (i.e. `FROM node:12.16.0-alpine`) *after* the build script
- [x] COPY the built production code into the new layer
- [x] Serve the react app on an exposed port (e.g. `CMD ["serve", "-s", "build", "-l", "3000"]`)

**Comment by hbh7** [comment]
Work on this is underway. I've pushed some changes to the Docker branch if you feel like taking a look early. If not, no worries, I will message again when the rest are complete.

**Comment by hbh7** [comment]
Issues resolved and merged
