### ISSUE TITLE
npm package security issues

### ISSUE THREAD

**Issue by MJGTwo** [hbh7/MITRGroupProject_Frontend#8]
when i pulled the changes for the `docker` branch and ran `npm install` i was notified of the following number of security issues:

`found 889 vulnerabilities (872 low, 17 moderate)`

This can be fixed with 1) removing `./node_module` and `package-lock.json` 2) rerunning `npm install` 3) verifying everything still functions with the fresh packages

**Comment by hbh7** [comment]
I noticed that too yesterday when working with the Docker things, planning on addressing it today.

**Comment by hbh7** [comment]
Fixed in 918c1852ffc08f547cf7a301372d5b3fb146707c
