### ISSUE TITLE
Uncaught Promise in Feed.tsx

### ISSUE THREAD

**Issue by MJGTwo** [hbh7/MITRGroupProject_Frontend#9]
Here's the traceback of the error. This error happens twice immediate upon starting in development.
```bash

Promise.then (async) |   |  
-- | -- | --
  | componentDidMount | @ | Feed.tsx:22
  | commitLifeCycles | @ | react-dom.development.js:19814
  | commitLayoutEffects | @ | react-dom.development.js:22803
  | callCallback | @ | react-dom.development.js:188
  | invokeGuardedCallbackDev | @ | react-dom.development.js:237
  | invokeGuardedCallback | @ | react-dom.development.js:292
  | commitRootImpl | @ | react-dom.development.js:22541
  | unstable_runWithPriority | @ | scheduler.development.js:653
  | runWithPriority$1 | @ | react-dom.development.js:11039
  | commitRoot | @ | react-dom.development.js:22381
  | finishSyncRender | @ | react-dom.development.js:21807
  | performSyncWorkOnRoot | @ | react-dom.development.js:21793
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21188
  | updateContainer | @ | react-dom.development.js:24373
  | (anonymous) | @ | react-dom.development.js:24758
  | unbatchedUpdates | @ | react-dom.development.js:21903
  | legacyRenderSubtreeIntoContainer | @ | react-dom.development.js:24757
  | render | @ | react-dom.development.js:24840
  | ./src/index.tsx | @ | index.tsx:7
  | __webpack_require__ | @ | bootstrap:785
  | fn | @ | bootstrap:150
  | 1 | @ | serviceWorker.ts:149
  | __webpack_require__ | @ | bootstrap:785
  | checkDeferredModules | @ | bootstrap:45
  | webpackJsonpCallback | @ | bootstrap:32
  | (anonymous) | @ | main.chunk.js:1


```

**Comment by MJGTwo** [comment]
so the issues seem to be these type of calls

App.tsx
```typescript
  componentDidMount() {
    fetch('/getUser')
      .then(response => response.json())
      .then(data => this.setState({ name: data.name, isAdmin: data.isAdmin }) );
  }
```

Feed.tsx
```typescript
  componentDidMount() {
    fetch('/getAPIs')
      .then(response => response.json())
      .then(data => this.setState({ apis: data.apis }) );
  }
```

The issue being you are giving no namespace/domain in reference to the path here. Thankfully having just looked at the backend code, i see these as paths from it but you have no api host or port mentioned here. instead of doing `fetch('/getAPIs')` you need to do something like `fetch('http://api_name/getAPIs')`. I should note here that you need to do more work than what I just did by incorporating environment variables such as `HTTP_METHOD` (being `http` or `https` ) and `API_DOMAIN` being the namespace of the API. If you need more direction let me know.

**Comment by hbh7** [comment]
I believe that's due to in-progress work on client to backend communication. Those are placeholders for the time being and are being updated over the course of this week. If you look in Login.tsx, you should see a more functional version. I had planned on making an environment variable BACKEND_URL or similar where that could be specified as I foresaw that being an issue as well.

**Comment by hbh7** [comment]
Should be resolved now. Will make 100% sure in testing phase shortly.
